name: TikTok Recorder Bot

on:
  schedule:
    # الأوقات هنا مكتوبة بتوقيت جرينتش (UTC) لتتوافق مع توقيت بغداد
    - cron: '0 6 * * *'    # يبدأ 9:00 صباحاً بتوقيت بغداد
    - cron: '30 11 * * *'  # يبدأ 2:30 ظهراً بتوقيت بغداد
    - cron: '0 17 * * *'   # يبدأ 8:00 مساءً بتوقيت بغداد
    - cron: '30 22 * * *'  # يبدأ 1:30 ليلاً بتوقيت بغداد
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py
