name: TikTok Recorder Bot

on:
  schedule:
    # الأوقات بتوقيت UTC مع تداخل 10 دقائق لضمان عدم انقطاع التسجيل
    - cron: '0 6 * * *'    # يبدأ 9:00 صباحاً بتوقيت بغداد
    - cron: '20 11 * * *'  # يبدأ 2:20 ظهراً (قبل توقف الأول بـ 10 دقائق)
    - cron: '40 16 * * *'  # يبدأ 7:40 مساءً (قبل توقف الثاني بـ 10 دقائق)
    - cron: '0 22 * * *'   # يبدأ 1:00 ليلاً (قبل توقف الثالث بـ 10 دقائق)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py
